SELECT
  v.TEST_ID,
  t.SUB_TYPE_PRODUCT_ID,
  t.SUB_KELOMPOK,
  t.KELOMPOK
FROM
  VOUCHER_EVENT_CONTRACT v
JOIN TEST_RELATED_DETAIL td ON v.TEST_ID = td.TEST_ID
JOIN TEST_RELATED tr ON v.TEST_ID = tr.TEST_ID
JOIN TEST_BY_CATEGORY tbc ON v.TEST_ID = tbc.TEST_ID
JOIN TEST_ALIAS ta ON v.TEST_ID = ta.TEST_ID
JOIN TEST_FINISH_TIME_PST tfp ON v.TEST_ID = tfp.TEST_ID
JOIN TEST_POPULAR tp ON v.TEST_ID = tp.TEST_ID
JOIN TEST_NEWEST tn ON v.TEST_ID = tn.TEST_ID
JOIN TEST_BY_SUBCATEGORY tbs ON v.TEST_ID = tbs.TEST_ID
JOIN HSPL_REG_RESULT hrr ON v.TEST_ID = hrr.TEST_ID
JOIN HPSL_TEST ht ON v.TEST_ID = ht.TEST_ID
JOIN TAX_TEST_PPN ttp ON v.TEST_ID = ttp.TEST_ID
JOIN TEST_FINISH_TIME tft ON v.TEST_ID = tft.TEST_ID
JOIN PAYMENT_PPN pp ON v.TEST_ID = pp.TEST_ID
JOIN TEST_ISOTERIK ti ON v.TEST_ID = ti.TEST_ID
JOIN TEST_INTENSIFIKASI ti2 ON v.TEST_ID = ti2.TEST_ID
JOIN TEST_UNPUBLISH tu ON v.TEST_ID = tu.TEST_ID
JOIN TEST_WHITELIST tw ON v.TEST_ID = tw.TEST_ID
JOIN TMP_PRICELIST tp2 ON v.TEST_ID = tp2.TEST_ID
JOIN PRM_TEST_GENOMIC ptg ON v.TEST_ID = ptg.TEST_ID
JOIN TEST_RESULT_CONVERSION trc ON v.TEST_ID = trc.TEST_ID
JOIN CUSEA_MASTER_HS cmh ON v.TEST_ID = cmh.TEST_ID
JOIN TEST_PERSIAPAN tp3 ON v.TEST_ID = tp3.TEST_ID
JOIN REG_AUTO_ACTION raa ON v.TEST_ID = raa.TEST_ID
JOIN TEST_REPORT tr2 ON v.TEST_ID = tr2.TEST_ID
JOIN TEST_BY_CONDITION_PMOL tbcp ON v.TEST_ID = tbcp.TEST_ID
JOIN TEST_SUB_DEPARTMENT tsd ON v.TEST_ID = tsd.TEST_ID
JOIN TEST_BY_SUBGROUP_CLINIC tbsc ON v.TEST_ID = tbsc.TEST_ID
JOIN TEST_HPS th ON v.TEST_ID = th.TEST_ID
JOIN TEST_BY_SUBCATEGORY_PRODUCT tbscp ON v.TEST_ID = tbscp.TEST_ID
JOIN SUB_TYPE_PRODUCT stp ON tbscp.SUB_TYPE_PRODUCT_ID = stp.SUB_TYPE_PRODUCT_ID 
JOIN TEST_DETAIL td2 ON v.TEST_ID = td2.TEST_ID
JOIN AUTO_USER_TEST aut ON v.TEST_ID = aut.TEST_ID
JOIN AUTO_TESTCOND atc ON v.TEST_ID = atc.TEST_ID
JOIN AUTO_TEST_ACTIVE ata ON v.TEST_ID = ata.TEST_ID
JOIN AUTO_TEST at ON v.TEST_ID = at.TEST_ID
JOIN TEST_KRITIS_KUALITATIF tkk ON v.TEST_ID = tkk.TEST_ID
JOIN AUTO_SAMPLE asam ON v.TEST_ID = asam.TEST_ID
JOIN AUTO_RANGE_KUALI ark ON v.TEST_ID = ark.TEST_ID
JOIN AUTO_RANGE ar ON v.TEST_ID = ar.TEST_ID
JOIN AUTO_FORMULA1 af1 ON v.TEST_ID = af1.TEST_ID
JOIN AUTO_FORMULA af ON v.TEST_ID = af.TEST_ID
JOIN AUTO_CN acn ON v.TEST_ID = acn.TEST_ID
JOIN AUTO_CC acc ON v.TEST_ID = acc.TEST_ID
JOIN AUTO_BATAS_RELEASE abr ON v.TEST_ID = abr.TEST_ID
JOIN TEST_PER_AWAM tpa ON v.TEST_ID = tpa.TEST_ID
JOIN PAYMENT_SMT1 ps1 ON v.TEST_ID = ps1.TEST_ID
JOIN PAYMENT_SMT ps ON v.TEST_ID = ps.TEST_ID
JOIN PROFILE_REKAP_ITEM pri ON v.TEST_ID = pri.TEST_ID
JOIN RPT_TEST_INSTRUMENT rti ON v.TEST_ID = rti.TEST_ID
JOIN RPT_TEST_PANEL rtp ON v.TEST_ID = rtp.TEST_ID
JOIN RPT_TEST rt ON v.TEST_ID = rt.TEST_ID
JOIN REQUISITION req ON v.TEST_ID = req.TEST_ID
JOIN REGTEST_CONDITION rtc ON v.TEST_ID = rtc.TEST_ID
JOIN REG_TEST rt2 ON v.TEST_ID = rt2.TEST_ID
JOIN PAYMENT_DOCTOR pd ON v.TEST_ID = pd.TEST_ID
JOIN PAYMENT pay ON v.TEST_ID = pay.TEST_ID
JOIN PHY_REQUISITION pr ON v.TEST_ID = pr.TEST_ID
JOIN REQ_RESULT rr ON v.TEST_ID = rr.TEST_ID
JOIN REQ_PRICE rp ON v.TEST_ID = rp.TEST_ID
JOIN REG_ORGANISM ro ON v.TEST_ID = ro.TEST_ID
JOIN WORKSHEET w ON v.TEST_ID = w.TEST_ID
JOIN INTERFACING_LINEARITAS il ON v.TEST_ID = il.TEST_ID
JOIN REF_RANGE_CONV rrc ON v.TEST_ID = rrc.TEST_ID
JOIN REF_RANGE_SI rrs ON v.TEST_ID = rrs.TEST_ID
JOIN TEST_UNIT tu2 ON v.TEST_ID = tu2.TEST_ID
JOIN TEST_TEMP tt ON v.TEST_ID = tt.TEST_ID
JOIN TEST_SUMMARY2 ts2 ON v.TEST_ID = ts2.TEST_ID
JOIN TEST_SUMMARY ts ON v.TEST_ID = ts.TEST_ID
JOIN TEST_SPECIMEN tsp ON v.TEST_ID = tsp.TEST_ID
JOIN TEST_RESULT tr3 ON v.TEST_ID = tr3.TEST_ID
JOIN TEST_REFLECT tref ON v.TEST_ID = tref.TEST_ID
JOIN TEST_PROCESS tp4 ON v.TEST_ID = tp4.TEST_ID
JOIN TEST_CATALOG tc ON v.TEST_ID = tc.TEST_ID
JOIN TEST_CONDITION tco ON v.TEST_ID = tco.TEST_ID
JOIN TEST_CALC tca ON v.TEST_ID = tca.TEST_ID
JOIN TEST_BUTTON tbut ON v.TEST_ID = tbut.TEST_ID
JOIN TEST_ANALYZER ta2 ON v.TEST_ID = ta2.TEST_ID
JOIN TEST_ALERT talert ON v.TEST_ID = talert.TEST_ID
JOIN TEST t ON v.TEST_ID = t.TEST_ID
JOIN TEMP_REQ trq ON v.TEST_ID = trq.TEST_ID
JOIN STABILITY st ON v.TEST_ID = st.TEST_ID
JOIN SPECIAL_PRICE sp ON v.TEST_ID = sp.TEST_ID
JOIN REQ_SPECIMEN rs ON v.TEST_ID = rs.TEST_ID
JOIN REQ_CHANGE_INSTRUMENT rci ON v.TEST_ID = rci.TEST_ID
JOIN REQ_CENTRAL rc ON v.TEST_ID = rc.TEST_ID
JOIN REG_SPECIMEN_MICRO rsm ON v.TEST_ID = rsm.TEST_ID
JOIN REG_ANTIBIOTIC ra ON v.TEST_ID = ra.TEST_ID
JOIN REGTEST_SPECIMEN rs2 ON v.TEST_ID = rs2.TEST_ID
JOIN REGTEST_SAMPLE rsam ON v.TEST_ID = rsam.TEST_ID
JOIN REF_RANGE rr2 ON v.TEST_ID = rr2.TEST_ID
JOIN REFERENCE_RANGE rrng ON v.TEST_ID = rrng.TEST_ID
JOIN PROFILE_ITEM pi ON v.TEST_ID = pi.TEST_ID
JOIN PRICE pr2 ON v.TEST_ID = pr2.TEST_ID
JOIN PHY_TEST_RESULT ptr ON v.TEST_ID = ptr.TEST_ID
JOIN PHY_TEST pt ON v.TEST_ID = pt.TEST_ID
JOIN PHY_PROFILE_ITEM ppi ON v.TEST_ID = ppi.TEST_ID
JOIN PHY_MASTER pm ON v.TEST_ID = pm.TEST_ID
JOIN PAYMENT_VOID pv ON v.TEST_ID = pv.TEST_ID
JOIN PANEL_ITEM pan ON v.TEST_ID = pan.TEST_ID
JOIN MULTIPLE_ITEM mi ON v.TEST_ID = mi.TEST_ID
JOIN INTERFACING_TEST it ON v.TEST_ID = it.TEST_ID
JOIN INSTRUMENT_TEST itest ON v.TEST_ID = itest.TEST_ID
JOIN DISCOUNT_ITEM di ON v.TEST_ID = di.TEST_ID
JOIN CONVERSION_UNIT cu ON v.TEST_ID = cu.TEST_ID
JOIN CONTRACT_PKG cp ON v.TEST_ID = cp.TEST_ID
JOIN CONC_TEST ct ON v.TEST_ID = ct.TEST_ID
JOIN BATCH_RESULT br ON v.TEST_ID = br.TEST_ID
JOIN KUISIONER_TEST kt ON v.TEST_ID = kt.TEST_ID
JOIN KUISIONER_REG_PATIENT krp ON v.TEST_ID = krp.TEST_ID
JOIN RPT_MARKETING_SALES_2 rms2 ON v.TEST_ID = rms2.TEST_ID
JOIN PYS pys ON v.TEST_ID = pys.TEST_ID
JOIN DLRVD_DETAIL dd ON v.TEST_ID = dd.TEST_ID
JOIN WSHP wshp ON v.TEST_ID = wshp.TEST_ID
JOIN SAMPLE_REQUIREMENT sr ON v.TEST_ID = sr.TEST_ID
JOIN CONTAINERS_DETAIL cd ON v.TEST_ID = cd.TEST_ID
JOIN TEST_TAGS ttg ON v.TEST_ID = ttg.TEST_ID
JOIN CUSEA_REG_PI_CS crcs ON v.TEST_ID = crcs.TEST_ID
JOIN CUSEA_MASTER cm ON v.TEST_ID = cm.TEST_ID
JOIN TEST_AUTOADD_DETAIL tad ON v.TEST_ID = tad.TEST_ID
JOIN TEST_PERMISSION tp5 ON v.TEST_ID = tp5.TEST_ID;



NOTE UNTUK 10.METATEST.TEST_MKT_new
ini ketemu untuk kolom yang bersinggungan tapi
untuk kolom
'SUB_KELOMPOK',
'KELOMPOK')
itu tidak ada... so This is Red table !

Dan kenapa table join diatas banyak karena itu table yang bersinggungan dengan kolom yang di minta
tapi tetap tidak search untuk kolom sub_kelompok dan kelompok